project:
  type: website
  resources:
    - CNAME
    - /assets

website:
  title: "bites | brews | paws"
  description: "A personal take on Chicago food, music, photography, and other topics."
  image: "/img/bites_brews_paws_logo.png"
  open-graph: 
    locale: es_ES
    site-name: "bites | brews | paws"
  twitter-card: true
  site-url: https://sinisterrob.github.io
  google-analytics: "G-TLJMCG2VMV"
  cookie-consent: false
  favicon: "/img/favicon.ico"
  navbar:
    left:
      - text: About Me
        href: about_me.qmd
      - text: Personal Reviews
        menu:
          - text: Food Reviews
            href: food_review.qmd
          - text: Music Reviews
            href: music_review.qmd
          - text: Book Reviews
            href: book_review.qmd
      - text: Blogs & Analysis
        menu:
          - text: Chess Analysis
            href: chess_analysis.qmd
          - text: Personal Blog
            href: personal_blog.qmd
          - text: Professional Blog
            href: professional_blog.qmd
      - text: Photography
        href: photography.qmd
    right:
      - text: Subscribe to bites | brews | paws!
        href: blog_subscribe.qmd

format:
  html:
    include-in-header:
      - text: <link href="https://iosevka-webfonts.github.io/iosevka/Iosevka.css" rel="stylesheet" />
    grid:
      margin-width: 425px
    theme: litera
    css: styles.css
    toc: true